### ISSUE TITLE
native _SET_PELT_FOR_HORSE_BY_INVENTORY_ITEM

### ISSUE THREAD

**Issue by Ultimationzzz** [VORPCORE/RDR3natives#2]
_SET_PELT_FOR_HORSE_BY_INVENTORY_ITEM is the wrong name, i am the one who submitted it to allocator.re

it should be, also, some credits should be added.

__SET_PELT_FOR_HORSE_WITH_TEXTURE

**Comment by outsider31000** [comment]
Exactly, you contributed there, not here,  make your prs here if you want some sort of credits this will be the most updated nativeDB.
And by alloc8tr comments that was the name he suggested.
we don't care who found what,  there's no need for all those technicalities. The only purpose here is to share.

If you want make a pr to change name.

**Comment by outsider31000** [comment]
Exactly, you contributed there, not here,  make your prs here if you want some sort of credits this will be the most updated nativeDB.
And by alloc8tr comments that was the name he suggested.
we don't care who found what,  there's no need for all those technicalities. The only purpose here is to share.

If you want make a pr to change name.

**Comment by outsider31000** [comment]
I can do whatever the fuck I want it's in a public repo lol.
Natives are also from rockstars  stop crying about something that isn't yours.

**Comment by outsider31000** [comment]
Didn't you even  see how many prs are there just sitting?
 imagine now having to wait for cfx and also waiting alloc8tr lol. That is the whole  reason this repo was create. They don't give a fuck. And we ain't waiting  we will update and it's available for everyone to contribute  so either contribute or don't share anything if you don't want others to use them.

**Comment by Ultimationzzz** [comment]
not crying, but yeah now i know why everyone i have talked to says you are a dick and that you have nobody even fucking pr to this repository, your attitude needs some work kid, The natives maybe rockstars, but nobody else spent the time I did in reverse engineering the undocumented natives I have and published them publicly, there is no fucking issue in giving people credit whom have spent their time on things, this repository is like your framework and discord, a mess, and complete shit.

**Comment by outsider31000** [comment]
Oh I'm the dick? You come here accusing people of stealing something that you claim yours, that you shared in a public repo? Go call the police then wtf. Ridiculous. 
Winning baby like the others. You came here on purpose just to start shit cause yall seem to not have anything better to do. 
Spent so much time finding 1 native think he has found  the cure to cancer or something.
Give me a fucking break.

**Comment by Ultimationzzz** [comment]
Actually i had a bunch to submit here, but after that shit, I won't bother, you are the first in your discord to start being vocal when you think people take shit from Vorp and don't even mention it was from vorp. Ive seen your messages, kinda 
hypocritical. Anyway, that is all i have to say, do as you wish, but don't expect this repo to take off with people like you running it.

**Comment by outsider31000** [comment]
You came here to start shit that was your point from the start.
Yall have nothing better to do.
Why didnt you made a pr to change the native name like I said?  Exactly.
Instead you came here wining about something that was added for everyone to use  and still wanted me to wait for alloc8tr to merge it first ???. What would be the point of this repo then ?
Yall do this on purpose cause hatting on me seems to be a fun hobby. 
You came here to start shit, just like all the others do... instead, I'm the bad guy,  for not letting a dumbass tell me what i should do or not on a public repo that we in vorp put our own time doing it, for everyone to use.

My energy will always match.
Next time  think about how you approach first, Instead of being offended for something you fucking started.
Fuck out of here dude.

**Comment by outsider31000** [comment]
You had so much to share that your first action was to come here winning. Please solve your own issues. You clearly have no idea how to contribute to a project if you think that is how you approach those who putting their free time for the good of RedM community.
